// app/layout.tsx
import type { ReactNode } from "react";
import "./globals.css";
import { TrpcProvider } from "@/client/TrpcProvider";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* tRPC + React Query providers, available to the whole app */}
        <TrpcProvider>{children}</TrpcProvider>
      </body>
    </html>
  );
}
